task: 'if_nerf'
gpus: [0]

parent_cfg: 'configs/zju_mocap_exp/latent_xyzc_313.yaml'

train_dataset:
    data_root: 'data/h36m/S7/Posing'
    human: 'S7'
    ann_file: 'data/h36m/S7/Posing/annots.npy'
    split: 'train'

test_dataset:
    data_root: 'data/h36m/S7/Posing'
    human: 'S7'
    ann_file: 'data/h36m/S7/Posing/annots.npy'
    split: 'test'

# data options
H: 1002
W: 1000
ratio: 1.
training_view: [0, 1, 2]
begin_ith_frame: 0
num_train_frame: 300
frame_interval: 5
smpl: 'smpl'
vertices: 'new_vertices'
params: 'new_params'
big_box: True
