task: 'if_nerf'
gpus: [0]

parent_cfg: 'configs/zju_mocap_exp/latent_xyzc_313.yaml'

human: 392

train_dataset:
    data_root: 'data/zju_mocap/CoreView_392'
    human: 'CoreView_392'
    ann_file: 'data/zju_mocap/CoreView_392/annots.npy'
    split: 'train'

test_dataset:
    data_root: 'data/zju_mocap/CoreView_392'
    human: 'CoreView_392'
    ann_file: 'data/zju_mocap/CoreView_392/annots.npy'
    split: 'test'

# data options
num_train_frame: 1
